FROM antonioglass/worker-a1111:runpod-base-xl-1.0.1

# Download Stable Diffusion models
WORKDIR /stable-diffusion-webui/models/Stable-diffusion
RUN wget https://huggingface.co/antonioglass/models/resolve/main/cyberrealisticPony_v62.safetensors && \
    wget https://huggingface.co/antonioglass/models/resolve/main/cyberrealisticPorn_v62_inpainting_vae.inpainting.safetensors

WORKDIR /