FROM antonioglass/worker-a1111-base-runpod:1.0.1

# Download Stable Diffusion models
WORKDIR /stable-diffusion-webui/models/Stable-diffusion
RUN wget https://huggingface.co/antonioglass/models/resolve/main/epicphotogasm_y.safetensors && \
    wget https://huggingface.co/antonioglass/models/resolve/main/semi-realistic_v6.safetensors && \
    wget https://huggingface.co/antonioglass/models/resolve/main/dreamshaper_631Inpainting.safetensors && \
    wget https://huggingface.co/antonioglass/models/resolve/main/epicphotogasm_z-inpainting.safetensors && \

# Download embeddings models
WORKDIR /stable-diffusion-webui/embeddings
RUN wget https://huggingface.co/antonioglass/embeddings/resolve/main/BadDream.pt && \
    wget https://huggingface.co/antonioglass/embeddings/resolve/main/FastNegativeV2.pt && \
    wget https://huggingface.co/antonioglass/embeddings/resolve/main/UnrealisticDream.pt

# Download LoRa models
WORKDIR /stable-diffusion-webui/models/Lora
RUN wget https://huggingface.co/antonioglass/loras/resolve/main/hand_in_panties_v0.82.safetensors && \
    wget https://huggingface.co/antonioglass/loras/resolve/main/jkSmallBreastsLite_V01.safetensors && \
    wget https://huggingface.co/antonioglass/loras/resolve/main/shirtliftv1.safetensors

WORKDIR /