FROM antonioglass/worker-a1111:runpod-base-xl-1.0.1

# Add RunPod Handler and Docker container start script
WORKDIR /
COPY start_salad.sh salad_handler.py ./

# Add Salad Job Queue Worker
ADD https://github.com/SaladTechnologies/salad-cloud-job-queue-worker/releases/download/v0.4.0/salad-http-job-queue-worker_x86_64.tar.gz /tmp
RUN tar -C /usr/local/bin -zxpf /tmp/salad-http-job-queue-worker_x86_64.tar.gz && \
    rm -rf /tmp/salad-http-job-queue-worker_x86_64.tar.gz

# Start the container
RUN chmod +x /start_salad.sh
ENTRYPOINT /start_salad.sh