FROM antonioglass/worker-a1111:runpod-nds-xl

WORKDIR /

ADD https://github.com/SaladTechnologies/salad-cloud-job-queue-worker/releases/download/v0.5.0/salad-http-job-queue-worker_x86_64.tar.gz /tmp
RUN tar -C /usr/local/bin -zxpf /tmp/salad-http-job-queue-worker_x86_64.tar.gz && \
    rm -rf /tmp/salad-http-job-queue-worker_x86_64.tar.gz

COPY salad_handler.py /
COPY start_salad.sh /

RUN chmod +x /start_salad.sh

ENTRYPOINT /start_salad.sh

# docker buildx build -f Dockerfile.salad-nds-xl -t antonioglass/worker-a1111:salad-nds-xl . --platform linux/amd64